variables:
  ACR_NAME: acrXXX.azurecr.io
  KV_NAME: KV-EUR-WW-POC-DL
  SERVICE_CONNECTION: ADO-SVC-CONN
  RESOURCE_GROUP: RG-EUR-WW-POC-DL
  CAP_ENV: CAP-EUR-WW-POC-DL
  LAW_NAME: OMS-EUR-WW-POC-DL
  IDN_NAME: CAP-IDN-EUR-WW-POC-DL
  AZP_URL: https://dev.azure.com/ORGANISATION
  CAP_POOL: cap-pool
  CAP_POOLID: 23